require "hokul.options"
require "hokul.keymaps"
require "hokul.plugins"
require "hokul.treesitter"
require "hokul.transparent"
require "hokul.cmp"
require "hokul.mason"
require "hokul.comment"
require "hokul.nvim-tree"
require "hokul.vimtex"
require "hokul.lualine"
vim.cmd "colorscheme darkplus"
